<<<<<<< HEAD
DATATOGRAB = "English/Spanish/English_Spanish.tsv"
DATATOSTORE = "English/Spanish/"
INPUTPATH = "../../data/raw/"
TRAINPATH = "../../data/processed/English/Spanish/Train/"
TESTPATH = "../../data/processed/English/Spanish/Test/"
LANGUAGES = ["English", "Spanish", "French", "German", "Korean", "Mandarin"]
CONTRACTIONS = {
    "i'm": "I am",
    "you're": "you are",
    "he's": "he is",
    "she's": "she is",
    "it's": "it is",
    "we're": "we are",
    "they're": "they are",
    "i've": "I have",
    "you've": "you have",
    "we've": "we have",
    "they've": "they have",
    "i'd": "I would",
    "you'd": "you would",
    "he'd": "he would",
    "she'd": "she would",
    "we'd": "we would",
    "they'd": "they would",
    "i'll": "I will",
    "you'll": "you will",
    "he'll": "he will",
    "she'll": "she will",
    "we'll": "we will",
    "they'll": "they will",
    "isn't": "is not",
    "aren't": "are not",
    "wasn't": "was not",
    "weren't": "were not",
    "hasn't": "has not",
    "haven't": "have not",
    "hadn't": "had not",
    "won't": "will not",
    "wouldn't": "would not",
    "can't": "cannot",
    "don't": "do not",
    "doesn't": "does not",
    "didn't": "did not",
    "shouldn't": "should not",
    "couldn't": "could not",
    "mightn't": "might not",
    "gonna": "going to",
    "wanna": "want to",
    "gotta": "got to",
    "hafta": "have to",
    "lemme": "let me",
    "ain't": "is not",
    "y'all": "you all",
    "y'know": "you know",
    "c'mon": "come on",
    "o'clock": "of the clock",
    "how'd": "how did",
    "how'll": "how will",
    "how're": "how are",
    "how's": "how is",
    "what'll": "what will",
    "what're": "what are",
    "what's": "what is",
    "when's": "when is",
    "where's": "where is",
    "who's": "who is",
    "why's": "why is",
    "that'll": "that will",
    "that're": "that are",
    "who'd": "who would",
    "who'll": "who will",
    "who've": "who have",
    "whatcha": "what are you",
    "whaddaya": "what do you",
    "could've": "could have",
    "should've": "should have",
    "would've": "would have",
    "might've": "might have",
    "must've": "must have",
    "oughtn't": "ought not",
    "shan't": "shall not",
    "needn't": "need not",
    "mustn't": "must not",
    "let's": "let us",
    "there's": "there is",
    "here's": "here is",
    "where's": "where is",
    "whenever": "when ever",
    "whatever": "what ever",
    "however": "in whatever way",
    "whosoever": "whoever",
    "whosoever's": "whosever's",
    "dunno": "do not know",
    "gimme": "give me",
    "gotcha": "got you",
    "imma": "I am going to",
    "kinda": "kind of",
    "lookit": "look at it",
    "mighta": "might have",
    "oughtta": "ought to",
    "shoulda": "should have",
    "supposedta": "supposed to",
    "t'ain't": "it is not",
    "woulda": "would have",
}



=======
DATATOGRAB = "English/Spanish/English_Spanish.tsv"
DATATOSTORE = "English/Spanish/"
INPUTPATH = "../../data/raw/"
TRAINPATH = "../../data/processed/English/Spanish/Train/"
TESTPATH = "../../data/processed/English/Spanish/Test/"
LANGUAGES = ["English", "Spanish", "French", "German", "Korean", "Mandarin"]
CONTRACTIONS = {
    "i'm": "I am",
    "you're": "you are",
    "he's": "he is",
    "she's": "she is",
    "it's": "it is",
    "we're": "we are",
    "they're": "they are",
    "i've": "I have",
    "you've": "you have",
    "we've": "we have",
    "they've": "they have",
    "i'd": "I would",
    "you'd": "you would",
    "he'd": "he would",
    "she'd": "she would",
    "we'd": "we would",
    "they'd": "they would",
    "i'll": "I will",
    "you'll": "you will",
    "he'll": "he will",
    "she'll": "she will",
    "we'll": "we will",
    "they'll": "they will",
    "isn't": "is not",
    "aren't": "are not",
    "wasn't": "was not",
    "weren't": "were not",
    "hasn't": "has not",
    "haven't": "have not",
    "hadn't": "had not",
    "won't": "will not",
    "wouldn't": "would not",
    "can't": "cannot",
    "don't": "do not",
    "doesn't": "does not",
    "didn't": "did not",
    "shouldn't": "should not",
    "couldn't": "could not",
    "mightn't": "might not",
    "gonna": "going to",
    "wanna": "want to",
    "gotta": "got to",
    "hafta": "have to",
    "lemme": "let me",
    "ain't": "is not",
    "y'all": "you all",
    "y'know": "you know",
    "c'mon": "come on",
    "o'clock": "of the clock",
    "how'd": "how did",
    "how'll": "how will",
    "how're": "how are",
    "how's": "how is",
    "what'll": "what will",
    "what're": "what are",
    "what's": "what is",
    "when's": "when is",
    "where's": "where is",
    "who's": "who is",
    "why's": "why is",
    "that'll": "that will",
    "that're": "that are",
    "who'd": "who would",
    "who'll": "who will",
    "who've": "who have",
    "whatcha": "what are you",
    "whaddaya": "what do you",
    "could've": "could have",
    "should've": "should have",
    "would've": "would have",
    "might've": "might have",
    "must've": "must have",
    "oughtn't": "ought not",
    "shan't": "shall not",
    "needn't": "need not",
    "mustn't": "must not",
    "let's": "let us",
    "there's": "there is",
    "here's": "here is",
    "where's": "where is",
    "whenever": "when ever",
    "whatever": "what ever",
    "however": "in whatever way",
    "whosoever": "whoever",
    "whosoever's": "whosever's",
    "dunno": "do not know",
    "gimme": "give me",
    "gotcha": "got you",
    "imma": "I am going to",
    "kinda": "kind of",
    "lookit": "look at it",
    "mighta": "might have",
    "oughtta": "ought to",
    "shoulda": "should have",
    "supposedta": "supposed to",
    "t'ain't": "it is not",
    "woulda": "would have",
}



>>>>>>> 46467f48de0d9b576e420d7ed6f02cd8a58f0e78
